package com.pookietalk.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

// import java.io.Serializable; // Removed redundant import
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
// Removed ", Serializable" as it's implied by UserDetails
public class User implements UserDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    @Column(unique = true, nullable = false)
    private String username;

    @NotBlank(message = "Password is required")
    // Consider removing password complexity validation here if handled elsewhere,
    // or ensure it matches requirements. Keeping it for now.
    @Size(min = 8, message = "Password must be at least 8 characters long")
    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$",
            message = "Password must contain at least one digit, one lowercase, one uppercase letter and one special character")
    @Column(nullable = false)
    private String password;

    @NotBlank(message = "Email is required")
    @Email(message = "Please provide a valid email address")
    @Column(unique = true, nullable = false)
    private String email;

    @NotNull(message = "Role is required")
    @Enumerated(EnumType.STRING)
    private Role role;

    // Added @Builder.Default for initialized collection
    @Builder.Default
    @ManyToMany(mappedBy = "participants")
    private Set<Chat> chats = new HashSet<>();

    // Added @Builder.Default for initialized booleans
    @Builder.Default
    @Column(nullable = false)
    private boolean accountNonExpired = true;

    @Builder.Default
    @Column(nullable = false)
    private boolean accountNonLocked = true;

    @Builder.Default
    @Column(nullable = false)
    private boolean credentialsNonExpired = true;

    @Builder.Default
    @Column(nullable = false)
    private boolean enabled = true;

    @Transient
    private String confirmPassword; // Often used in DTOs, ensure it's needed here

    // For mapping by ID only
    public User(Long id) {
        this.id = id;
    }

    // Custom constructor for test setup or manual object creation
    // Note: Lombok's @AllArgsConstructor already creates a constructor for all fields.
    // This custom one might conflict or be redundant unless specifically needed.
    // Keeping it as it was provided.
    public User(Long id, String username, String password, String email, Role role) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
        // Initialize chats here too if using this constructor
        this.chats = new HashSet<>();
        // Initialize boolean flags if needed for this constructor
        this.accountNonExpired = true;
        this.accountNonLocked = true;
        this.credentialsNonExpired = true;
        this.enabled = true;
    }


    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // Ensure Role enum name matches expected Spring Security format (e.g., "USER", "ADMIN")
        return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
    }

    // These getters are generated by Lombok @Data, but implementing them
    // explicitly for UserDetails interface is fine.
    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public String getUsername() {
        return username;
    }

    @Override
    public boolean isAccountNonExpired() {
        return accountNonExpired;
    }

    @Override
    public boolean isAccountNonLocked() {
        return accountNonLocked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }
}
