version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pookietalk_db
    restart: always
    environment:
      POSTGRES_USER: pookieuser
      POSTGRES_PASSWORD: pookiepass
      POSTGRES_DB: pookietalk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  backend:
    build: .
    container_name: pookietalk_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pookietalk
      SPRING_DATASOURCE_USERNAME: pookieuser
      SPRING_DATASOURCE_PASSWORD: pookiepass
    ports:
      - "8080:8080"

volumes:
  postgres_data:
