server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pookietalk_v2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: SecurePassword123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ✅ Create/update schema without dropping existing data
    show-sql: true # Optional: shows SQL queries for debugging
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    jwt:
      secret: ${JWT_SECRET:aVeryLongAndSecureJwtSecretKeyThatIsAtLeast32BytesLong}
      expiration: 86400000

cors:
  allowed-origins: "http://localhost:5173,http://127.0.0.1:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type"
  exposed-headers: "Authorization"

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.security: DEBUG   # ✅ Enables detailed security logs
    com.pookietalk: DEBUG                 # ✅ Your app logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
